apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: qa.com
    http:
      paths:
        - path: /
          backend:
            serviceName: hello-world-service
            servicePort: 8080