apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: argocd.com
    http:
      paths:
        - path: /
          backend:
            serviceName: argocd-server
            servicePort: 80